=== solobuilderhub/TF-knowledge-base/sources/tra-spec/AlbertaCorporateIncomeTaxReturn.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wmh="http://www.wmhelp.com/2003/eGenerator"
elementFormDefault="qualified">
  <!--
*******************************************************************
 *
 *    Produced by Treasury Board and Finance / Tax and Revenue Administration
 *    for Alberta Corprate Income Tax Returns.
 *
 *    Version Number 0.09
 *    November 19, 2010
 ******************************************************************
 -->
  <xs:element name="ReturnSubmission">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Return"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Return">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ProgramCode"/>
        <xs:element ref="Schedule" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ProgramCode" type="ProgramCode"/>
  <xs:element name="Schedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Value" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="Number" type="ScheduleNumber" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Value">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="ValueString">
          <xs:attribute name="LineItemID" type="LineItemID" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="ProgramCode">
    <xs:restriction base="xs:string">
      <xs:length value="2"/>
      <xs:pattern value="[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="LineItemID">
    <xs:restriction base="xs:string">
      <xs:length value="9"/>
      <xs:pattern value="\w{3}[0-9]{6}"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="ValueString">
    <xs:restriction base="xs:string">
      <xs:maxLength value="175"/>
    </xs:restriction>
  </xs:simpleType>



  <xs:simpleType name="ScheduleNumber">
    <xs:restriction base="xs:string">
      <xs:length value="3"/>
      <xs:pattern value="\w{3}"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== solobuilderhub/TF-knowledge-base/validation/tra-test-cases-fall-2026/tc1-netfile.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ReturnSubmission xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AlbertaCorporateIncomeTaxReturn.xsd">
  <Return>
    <ProgramCode>01</ProgramCode>
  <Schedule Number="000">
    <Value LineItemID="000001001">2</Value>
    <Value LineItemID="000005001">HL2026</Value>
    <Value LineItemID="000010001">Foothills Manufacturing Ltd.</Value>
    <Value LineItemID="000012001">1200 Stephen Avenue SW</Value>
    <Value LineItemID="000014001">Calgary</Value>
    <Value LineItemID="000015001">AB</Value>
    <Value LineItemID="000017001">T2P 5C5</Value>
    <Value LineItemID="000025001">Dana Whitecourt</Value>
    <Value LineItemID="000026001">4035550142</Value>
    <Value LineItemID="000028001">Industrial manufacturing</Value>
    <Value LineItemID="000029001">1</Value>
    <Value LineItemID="000031001">2</Value>
    <Value LineItemID="000032001">2</Value>
    <Value LineItemID="000034001">424102952</Value>
    <Value LineItemID="000035001">742518963</Value>
    <Value LineItemID="000036001">20240901</Value>
    <Value LineItemID="000037001">20250831</Value>
    <Value LineItemID="000038001">2</Value>
    <Value LineItemID="000047001">1000000</Value>
    <Value LineItemID="000048001">1665000</Value>
    <Value LineItemID="000050001">2</Value>
    <Value LineItemID="000054001">2</Value>
    <Value LineItemID="000060001">1</Value>
    <Value LineItemID="000061001">1</Value>
    <Value LineItemID="000062001">0</Value>
    <Value LineItemID="000064001">0</Value>
    <Value LineItemID="000065001">1.000000</Value>
    <Value LineItemID="000068001">0</Value>
    <Value LineItemID="000070001">0</Value>
    <Value LineItemID="000071001">0</Value>
    <Value LineItemID="000072001">0</Value>
    <Value LineItemID="000074001">0</Value>
    <Value LineItemID="000076001">0</Value>
    <Value LineItemID="000080001">0</Value>
    <Value LineItemID="000081001">0</Value>
    <Value LineItemID="000082001">0</Value>
    <Value LineItemID="000085001">0</Value>
    <Value LineItemID="000086001">0</Value>
    <Value LineItemID="000087001">0</Value>
    <Value LineItemID="000090001">0</Value>
    <Value LineItemID="000091001">0</Value>
    <Value LineItemID="000095001">1</Value>
    <Value LineItemID="000115001">0</Value>
    <Value LineItemID="000129001">0</Value>
    <Value LineItemID="000097001">Dana</Value>
    <Value LineItemID="000098001">Whitecourt</Value>
    <Value LineItemID="000099001">President</Value>
    <Value LineItemID="000101001">20260830</Value>
    <Value LineItemID="000103001">4035550142</Value>
    <Value LineItemID="000105001">dana.whitecourt@foothillsmfg.test</Value>
  </Schedule>
  <Schedule Number="001">
    <Value LineItemID="001003001">271200</Value>
    <Value LineItemID="001007001">271200</Value>
    <Value LineItemID="001009001">0</Value>
    <Value LineItemID="001013001">0</Value>
  </Schedule>
  <Schedule Number="010">
    <Value LineItemID="010003001">2024-08-30T18:00:00.000Z</Value>
    <Value LineItemID="010005001">2023-08-30T18:00:00.000Z</Value>
    <Value LineItemID="010007001">2022-08-30T18:00:00.000Z</Value>
    <Value LineItemID="010002001">19800</Value>
    <Value LineItemID="010004001">10000</Value>
    <Value LineItemID="010006001">3000</Value>
    <Value LineItemID="010008001">2500</Value>
    <Value LineItemID="010010001">4300</Value>
    <Value LineItemID="010042001">75000</Value>
    <Value LineItemID="010044001">12500</Value>
    <Value LineItemID="010046001">12500</Value>
    <Value LineItemID="010048001">12500</Value>
  </Schedule>
  <Schedule Number="012">
    <Value LineItemID="012002001">-19800</Value>
    <Value LineItemID="012004001">306200</Value>
    <Value LineItemID="012005001">301000</Value>
    <Value LineItemID="012054001">-25000</Value>
  </Schedule>
  <Schedule Number="013">
    <Value LineItemID="013001001">1</Value>
    <Value LineItemID="013019001">200</Value>
    <Value LineItemID="013015001">0</Value>
    <Value LineItemID="013017001">0</Value>
    <Value LineItemID="013021001">4800</Value>
    <Value LineItemID="013001002">8</Value>
    <Value LineItemID="013019002">301000</Value>
    <Value LineItemID="013015002">0</Value>
    <Value LineItemID="013017002">0</Value>
    <Value LineItemID="013021002">704000</Value>
    <Value LineItemID="013001003">13</Value>
    <Value LineItemID="013019003">5000</Value>
    <Value LineItemID="013015003">0</Value>
    <Value LineItemID="013017003">0</Value>
    <Value LineItemID="013021003">0</Value>
    <Value LineItemID="013023001">0</Value>
    <Value LineItemID="013025001">0</Value>
    <Value LineItemID="013027001">306200</Value>
  </Schedule>
  <Schedule Number="018">
    <Value LineItemID="018002001">100000</Value>
    <Value LineItemID="018022001">250000</Value>
    <Value LineItemID="018042001">0</Value>
    <Value LineItemID="018054001">-150000</Value>
    <Value LineItemID="018004001">0</Value>
    <Value LineItemID="018024001">0</Value>
    <Value LineItemID="018044001">0</Value>
    <Value LineItemID="018055001">0</Value>
    <Value LineItemID="018006001">0</Value>
    <Value LineItemID="018026001">0</Value>
    <Value LineItemID="018046001">0</Value>
    <Value LineItemID="018056001">0</Value>
    <Value LineItemID="018008001">0</Value>
    <Value LineItemID="018028001">0</Value>
    <Value LineItemID="018048001">0</Value>
    <Value LineItemID="018057001">0</Value>
    <Value LineItemID="018010001">0</Value>
    <Value LineItemID="018030001">0</Value>
    <Value LineItemID="018050001">0</Value>
    <Value LineItemID="018058001">0</Value>
    <Value LineItemID="018012001">0</Value>
    <Value LineItemID="018032001">0</Value>
    <Value LineItemID="018052001">0</Value>
    <Value LineItemID="018059001">0</Value>
    <Value LineItemID="018060001">0</Value>
    <Value LineItemID="018066001">0</Value>
    <Value LineItemID="018068001">0</Value>
    <Value LineItemID="018076001">0</Value>
    <Value LineItemID="018094001">0</Value>
  </Schedule>
  <Schedule Number="021">
    <Value LineItemID="021021001">25000</Value>
    <Value LineItemID="021031001">100000</Value>
    <Value LineItemID="021032001">0</Value>
    <Value LineItemID="021033001">100000</Value>
    <Value LineItemID="021035001">0</Value>
    <Value LineItemID="021037001">25000</Value>
    <Value LineItemID="021041001">0</Value>
    <Value LineItemID="021043001">0</Value>
    <Value LineItemID="021045001">0</Value>
    <Value LineItemID="021047001">15500</Value>
    <Value LineItemID="021049001">109500</Value>
    <Value LineItemID="021051001">100000</Value>
    <Value LineItemID="021055001">0</Value>
    <Value LineItemID="021057001">75000</Value>
    <Value LineItemID="021061001">0</Value>
    <Value LineItemID="021063001">0</Value>
    <Value LineItemID="021065001">0</Value>
    <Value LineItemID="021067001">75000</Value>
    <Value LineItemID="021069001">100000</Value>
    <Value LineItemID="021071001">0</Value>
    <Value LineItemID="021072001">0</Value>
    <Value LineItemID="021073001">0</Value>
    <Value LineItemID="021075001">0</Value>
    <Value LineItemID="021077001">0</Value>
    <Value LineItemID="021079001">0</Value>
    <Value LineItemID="021081001">0</Value>
    <Value LineItemID="021083001">0</Value>
    <Value LineItemID="021085001">0</Value>
    <Value LineItemID="021087001">0</Value>
    <Value LineItemID="021091001">0</Value>
    <Value LineItemID="021092001">0</Value>
    <Value LineItemID="021093001">0</Value>
    <Value LineItemID="021095001">0</Value>
    <Value LineItemID="021097001">0</Value>
    <Value LineItemID="021101001">0</Value>
    <Value LineItemID="021103001">0</Value>
    <Value LineItemID="021105001">0</Value>
    <Value LineItemID="021107001">0</Value>
    <Value LineItemID="021111001">0</Value>
    <Value LineItemID="021113001">0</Value>
    <Value LineItemID="021115001">0</Value>
    <Value LineItemID="021117001">0</Value>
    <Value LineItemID="021119001">0</Value>
    <Value LineItemID="021121001">0</Value>
    <Value LineItemID="021123001">0</Value>
    <Value LineItemID="021125001">0</Value>
    <Value LineItemID="021151001">0</Value>
    <Value LineItemID="021155001">0</Value>
    <Value LineItemID="021157001">25000</Value>
    <Value LineItemID="021159001">0</Value>
    <Value LineItemID="021165001">15500</Value>
    <Value LineItemID="021167001">0</Value>
    <Value LineItemID="021169001">9500</Value>
  </Schedule>
  <Schedule Number="EDI">
    <Value LineItemID="EDI001001">HL2026</Value>
    <Value LineItemID="EDI011001">0.0.1</Value>
    <Value LineItemID="EDI013001">0.1.0</Value>
    <Value LineItemID="EDI015001">SR_DEV</Value>
    <Value LineItemID="EDI017001">1</Value>
    <Value LineItemID="EDI019001">TaxFoundry Inc.</Value>
    <Value LineItemID="EDI031001">TaxFoundry</Value>
    <Value LineItemID="EDI033001">Support</Value>
    <Value LineItemID="EDI035001">Transmitter</Value>
    <Value LineItemID="EDI037001">0000000000</Value>
    <Value LineItemID="EDI041001">filing@taxfoundry.ca</Value>
  </Schedule>
  </Return>
</ReturnSubmission>

=== solobuilderhub/TF-knowledge-base/validation/tra-test-cases-fall-2026/tc3-netfile.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ReturnSubmission xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AlbertaCorporateIncomeTaxReturn.xsd">
  <Return>
    <ProgramCode>01</ProgramCode>
  <Schedule Number="000">
    <Value LineItemID="000001001">1</Value>
    <Value LineItemID="000005001">HL2026</Value>
    <Value LineItemID="000010001">Cascade Research Corp.</Value>
    <Value LineItemID="000012001">888 3 Street SW</Value>
    <Value LineItemID="000014001">Calgary</Value>
    <Value LineItemID="000015001">AB</Value>
    <Value LineItemID="000017001">T2P 5C5</Value>
    <Value LineItemID="000025001">Marcus Reyes</Value>
    <Value LineItemID="000026001">4035550164</Value>
    <Value LineItemID="000028001">5417</Value>
    <Value LineItemID="000029001">1</Value>
    <Value LineItemID="000031001">2</Value>
    <Value LineItemID="000032001">2</Value>
    <Value LineItemID="000034001">424102978</Value>
    <Value LineItemID="000035001">926318475RC0001</Value>
    <Value LineItemID="000036001">20250101</Value>
    <Value LineItemID="000037001">20251231</Value>
    <Value LineItemID="000038001">2</Value>
    <Value LineItemID="000047001">1500000</Value>
    <Value LineItemID="000048001">1400000</Value>
    <Value LineItemID="000050001">2</Value>
    <Value LineItemID="000054001">2</Value>
    <Value LineItemID="000060001">2</Value>
    <Value LineItemID="000061001">2</Value>
    <Value LineItemID="000062001">0</Value>
    <Value LineItemID="000064001">0</Value>
    <Value LineItemID="000065001">1.000000</Value>
    <Value LineItemID="000068001">0</Value>
    <Value LineItemID="000070001">0</Value>
    <Value LineItemID="000071001">0</Value>
    <Value LineItemID="000072001">0</Value>
    <Value LineItemID="000074001">0</Value>
    <Value LineItemID="000076001">0</Value>
    <Value LineItemID="000080001">0</Value>
    <Value LineItemID="000081001">0</Value>
    <Value LineItemID="000082001">0</Value>
    <Value LineItemID="000085001">0</Value>
    <Value LineItemID="000086001">0</Value>
    <Value LineItemID="000087001">0</Value>
    <Value LineItemID="000090001">0</Value>
    <Value LineItemID="000091001">0</Value>
    <Value LineItemID="000095001">1</Value>
    <Value LineItemID="000115001">0</Value>
    <Value LineItemID="000129001">89250</Value>
    <Value LineItemID="000097001">Marcus</Value>
    <Value LineItemID="000098001">Reyes</Value>
    <Value LineItemID="000099001">Chief Financial Officer</Value>
    <Value LineItemID="000101001">20260829</Value>
    <Value LineItemID="000103001">4035550164</Value>
    <Value LineItemID="000105001">marcus.reyes@cascaderesearch.test</Value>
  </Schedule>
  <Schedule Number="001">
    <Value LineItemID="001003001">0</Value>
    <Value LineItemID="001007001">0</Value>
    <Value LineItemID="001009001">0</Value>
    <Value LineItemID="001013001">0</Value>
  </Schedule>
  <Schedule Number="029">
    <Value LineItemID="029003001">1500000</Value>
    <Value LineItemID="029005001">1000000</Value>
    <Value LineItemID="029031001">1000000</Value>
    <Value LineItemID="029040001">2</Value>
    <Value LineItemID="029110001">80000</Value>
    <Value LineItemID="029125001">39000</Value>
    <Value LineItemID="029126001">20000000</Value>
    <Value LineItemID="029128001">0.750000</Value>
    <Value LineItemID="029130001">89250</Value>
    <Value LineItemID="029134001">89250</Value>
    <Value LineItemID="029200001">700200300</Value>
    <Value LineItemID="029202001">2024-07-01</Value>
    <Value LineItemID="029204001">2025-06-30</Value>
    <Value LineItemID="029206001">365</Value>
    <Value LineItemID="029208001">4000000</Value>
    <Value LineItemID="029230001">424102978</Value>
    <Value LineItemID="029235001">2025-12-31</Value>
    <Value LineItemID="029240001">3000000</Value>
    <Value LineItemID="029245001">1000000</Value>
    <Value LineItemID="029250001">750000</Value>
    <Value LineItemID="029260001">600000</Value>
    <Value LineItemID="029265001">10000000</Value>
    <Value LineItemID="029267001">325000</Value>
    <Value LineItemID="029268001">325000</Value>
    <Value LineItemID="029230002">700200300</Value>
    <Value LineItemID="029235002">2025-06-30</Value>
    <Value LineItemID="029240002">1000000</Value>
    <Value LineItemID="029245002">200000</Value>
    <Value LineItemID="029250002">0</Value>
    <Value LineItemID="029260002">500000</Value>
    <Value LineItemID="029265002">3000000</Value>
    <Value LineItemID="029267002">-50000</Value>
    <Value LineItemID="029268002">0</Value>
    <Value LineItemID="029230003">700300400</Value>
    <Value LineItemID="029235003">2025-09-30</Value>
    <Value LineItemID="029240003">0</Value>
    <Value LineItemID="029245003">100000</Value>
    <Value LineItemID="029250003">80000</Value>
    <Value LineItemID="029260003">0</Value>
    <Value LineItemID="029265003">5000000</Value>
    <Value LineItemID="029267003">60000</Value>
    <Value LineItemID="029268003">0</Value>
    <Value LineItemID="029230004">700400500</Value>
    <Value LineItemID="029235004">2025-03-31</Value>
    <Value LineItemID="029240004">0</Value>
    <Value LineItemID="029245004">0</Value>
    <Value LineItemID="029250004">0</Value>
    <Value LineItemID="029260004">0</Value>
    <Value LineItemID="029265004">2000000</Value>
    <Value LineItemID="029267004">0</Value>
    <Value LineItemID="029268004">0</Value>
    <Value LineItemID="029270001">4000000</Value>
    <Value LineItemID="029275001">1300000</Value>
    <Value LineItemID="029280001">830000</Value>
    <Value LineItemID="029290001">1100000</Value>
    <Value LineItemID="029300001">20000000</Value>
    <Value LineItemID="029310001">335000</Value>
    <Value LineItemID="029320001">325000</Value>
    <Value LineItemID="029325001">325000</Value>
  </Schedule>
  <Schedule Number="4970">
    <Value LineItemID="4970101001">Next-generation materials research programme</Value>
    <Value LineItemID="4970103001">2.04.01</Value>
    <Value LineItemID="4970105001">1000000</Value>
    <Value LineItemID="4970107001">500000</Value>
    <Value LineItemID="4970109001">400000</Value>
    <Value LineItemID="4970105002">1000000</Value>
    <Value LineItemID="4970107002">500000</Value>
    <Value LineItemID="4970109002">400000</Value>
    <Value LineItemID="4970111002">0</Value>
    <Value LineItemID="4970113002">0</Value>
    <Value LineItemID="4970135001">1000000</Value>
    <Value LineItemID="4970137001">500000</Value>
    <Value LineItemID="4970170001">1500000</Value>
  </Schedule>
  <Schedule Number="EDI">
    <Value LineItemID="EDI001001">HL2026</Value>
    <Value LineItemID="EDI011001">0.0.1</Value>
    <Value LineItemID="EDI013001">0.1.0</Value>
    <Value LineItemID="EDI015001">SR_DEV</Value>
    <Value LineItemID="EDI017001">1</Value>
    <Value LineItemID="EDI019001">TaxFoundry Inc.</Value>
    <Value LineItemID="EDI031001">TaxFoundry</Value>
    <Value LineItemID="EDI033001">Support</Value>
    <Value LineItemID="EDI035001">Transmitter</Value>
    <Value LineItemID="EDI037001">0000000000</Value>
    <Value LineItemID="EDI041001">filing@taxfoundry.ca</Value>
  </Schedule>
  </Return>
</ReturnSubmission>

=== solobuilderhub/TF-knowledge-base/validation/tra-test-cases-fall-2026/tc2-netfile.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ReturnSubmission xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AlbertaCorporateIncomeTaxReturn.xsd">
  <Return>
    <ProgramCode>01</ProgramCode>
  <Schedule Number="000">
    <Value LineItemID="000001001">1</Value>
    <Value LineItemID="000005001">HL2026</Value>
    <Value LineItemID="000010001">Aurora Innovations Ltd.</Value>
    <Value LineItemID="000012001">450 Jasper Avenue NW</Value>
    <Value LineItemID="000014001">Edmonton</Value>
    <Value LineItemID="000015001">AB</Value>
    <Value LineItemID="000017001">T5J 3N4</Value>
    <Value LineItemID="000025001">Priya Kaur</Value>
    <Value LineItemID="000026001">7805550188</Value>
    <Value LineItemID="000028001">5417</Value>
    <Value LineItemID="000029001">1</Value>
    <Value LineItemID="000031001">2</Value>
    <Value LineItemID="000032001">2</Value>
    <Value LineItemID="000034001">424102960</Value>
    <Value LineItemID="000035001">813574269RC0001</Value>
    <Value LineItemID="000036001">20250101</Value>
    <Value LineItemID="000037001">20251231</Value>
    <Value LineItemID="000038001">2</Value>
    <Value LineItemID="000047001">1000000</Value>
    <Value LineItemID="000048001">1000000</Value>
    <Value LineItemID="000050001">2</Value>
    <Value LineItemID="000054001">2</Value>
    <Value LineItemID="000060001">2</Value>
    <Value LineItemID="000061001">2</Value>
    <Value LineItemID="000062001">0</Value>
    <Value LineItemID="000064001">0</Value>
    <Value LineItemID="000065001">1.000000</Value>
    <Value LineItemID="000068001">0</Value>
    <Value LineItemID="000070001">0</Value>
    <Value LineItemID="000071001">0</Value>
    <Value LineItemID="000072001">0</Value>
    <Value LineItemID="000074001">0</Value>
    <Value LineItemID="000076001">0</Value>
    <Value LineItemID="000080001">0</Value>
    <Value LineItemID="000081001">0</Value>
    <Value LineItemID="000082001">0</Value>
    <Value LineItemID="000085001">0</Value>
    <Value LineItemID="000086001">0</Value>
    <Value LineItemID="000087001">0</Value>
    <Value LineItemID="000090001">0</Value>
    <Value LineItemID="000091001">0</Value>
    <Value LineItemID="000095001">1</Value>
    <Value LineItemID="000115001">0</Value>
    <Value LineItemID="000129001">31250</Value>
    <Value LineItemID="000097001">Priya</Value>
    <Value LineItemID="000098001">Kaur</Value>
    <Value LineItemID="000099001">Chief Executive Officer</Value>
    <Value LineItemID="000101001">20260829</Value>
    <Value LineItemID="000103001">7805550188</Value>
    <Value LineItemID="000105001">priya.kaur@aurorainnov.test</Value>
  </Schedule>
  <Schedule Number="001">
    <Value LineItemID="001003001">0</Value>
    <Value LineItemID="001007001">0</Value>
    <Value LineItemID="001009001">0</Value>
    <Value LineItemID="001013001">0</Value>
  </Schedule>
  <Schedule Number="029">
    <Value LineItemID="029003001">1000000</Value>
    <Value LineItemID="029005001">400000</Value>
    <Value LineItemID="029031001">400000</Value>
    <Value LineItemID="029040001">2</Value>
    <Value LineItemID="029110001">32000</Value>
    <Value LineItemID="029125001">18000</Value>
    <Value LineItemID="029126001">25000000</Value>
    <Value LineItemID="029128001">0.625000</Value>
    <Value LineItemID="029130001">31250</Value>
    <Value LineItemID="029134001">31250</Value>
    <Value LineItemID="029200001">700100200</Value>
    <Value LineItemID="029202001">2024-07-01</Value>
    <Value LineItemID="029204001">2025-06-30</Value>
    <Value LineItemID="029206001">365</Value>
    <Value LineItemID="029208001">4000000</Value>
    <Value LineItemID="029230001">424102960</Value>
    <Value LineItemID="029235001">2025-12-31</Value>
    <Value LineItemID="029240001">3000000</Value>
    <Value LineItemID="029245001">400000</Value>
    <Value LineItemID="029250001">300000</Value>
    <Value LineItemID="029260001">200000</Value>
    <Value LineItemID="029265001">12000000</Value>
    <Value LineItemID="029267001">150000</Value>
    <Value LineItemID="029268001">150000</Value>
    <Value LineItemID="029230002">700100200</Value>
    <Value LineItemID="029235002">2025-06-30</Value>
    <Value LineItemID="029240002">1000000</Value>
    <Value LineItemID="029245002">400000</Value>
    <Value LineItemID="029250002">150000</Value>
    <Value LineItemID="029260002">100000</Value>
    <Value LineItemID="029265002">13000000</Value>
    <Value LineItemID="029267002">275000</Value>
    <Value LineItemID="029268002">275000</Value>
    <Value LineItemID="029270001">4000000</Value>
    <Value LineItemID="029275001">800000</Value>
    <Value LineItemID="029280001">450000</Value>
    <Value LineItemID="029290001">300000</Value>
    <Value LineItemID="029300001">25000000</Value>
    <Value LineItemID="029310001">425000</Value>
    <Value LineItemID="029320001">425000</Value>
    <Value LineItemID="029325001">150000</Value>
  </Schedule>
  <Schedule Number="4970">
    <Value LineItemID="4970101001">Advanced process automation platform</Value>
    <Value LineItemID="4970103001">2.11.03</Value>
    <Value LineItemID="4970105001">400000</Value>
    <Value LineItemID="4970107001">600000</Value>
    <Value LineItemID="4970109001">100000</Value>
    <Value LineItemID="4970105002">400000</Value>
    <Value LineItemID="4970107002">600000</Value>
    <Value LineItemID="4970109002">100000</Value>
    <Value LineItemID="4970111002">0</Value>
    <Value LineItemID="4970113002">0</Value>
    <Value LineItemID="4970135001">400000</Value>
    <Value LineItemID="4970151001">600000</Value>
    <Value LineItemID="4970170001">1000000</Value>
  </Schedule>
  <Schedule Number="EDI">
    <Value LineItemID="EDI001001">HL2026</Value>
    <Value LineItemID="EDI011001">0.0.1</Value>
    <Value LineItemID="EDI013001">0.1.0</Value>
    <Value LineItemID="EDI015001">SR_DEV</Value>
    <Value LineItemID="EDI017001">1</Value>
    <Value LineItemID="EDI019001">TaxFoundry Inc.</Value>
    <Value LineItemID="EDI031001">TaxFoundry</Value>
    <Value LineItemID="EDI033001">Support</Value>
    <Value LineItemID="EDI035001">Transmitter</Value>
    <Value LineItemID="EDI037001">0000000000</Value>
    <Value LineItemID="EDI041001">filing@taxfoundry.ca</Value>
  </Schedule>
  </Return>
</ReturnSubmission>
